backstage:
  backstage:
    appConfig:
      app:
        baseUrl: http://localhost:3000
      backend:
        baseUrl: http://localhost:7007
        database:
          client: better-sqlite3
          connection: ':memory:'
      catalog:
        rules:
          - allow: [API, Component, Domain, Location, Resource, System]
        locations:
          - type: url
            target: https://github.com/abaguas/itplatform/blob/main/catalog/domains/all.yaml
          - type: url
            target: https://github.com/abaguas/itplatform/blob/main/catalog/systems/all.yaml
          - type: url
            target: https://github.com/abaguas/itplatform/blob/main/catalog/components/all.yaml
      organization:
        name: IT Platform
      techdocs:
        builder: local
        generator:
          runIn: local
        publisher:
          type: local
    image:
      pullPolicy: IfNotPresent
      registry: ''
      repository: backstage
      tag: mkdocs
