site_name: Backstage Docs
site_description: Main documentation for Backstage

nav:
  - Backstage:
    - Vanilla Backstage: 'backstage/vanilla-backstage.md'
    - Enable Techdocs: 'backstage/enable-techdocs.md'
  - Kubernetes:
    - Local Development: 'kubernetes/local-development.md'


plugins:
  - techdocs-core
